server:
  port: 7777

spring:
  application:
    name: ms-gateway

  cloud:
    gateway:
      routes:
        - id: route1
          predicates:
            - Path=/ms-group/**
          filters:
            - RewritePath=/ms-group/(?<s>.*), /${s}
          uri: lb://ms-group

        - id: route2
          predicates:
            - Path=/auth-service/**
          filters:
            - RewritePath=/auth-service/(?<s>.*), /${s}
          uri: lb://auth-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8888/eureka


